language: node_js

os:
    - linux
    - osx

node_js:
    - "8.11"
    - "9.0"
    - "10.0"

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb && sudo dpkg -i ripgrep_0.8.1_amd64.deb; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ripgrep; fi
    - npm run build
    - chmod a+x ./dist/src/main.js

install:
    - npm install
